import pandas as pd

from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework import status

from django.http import HttpResponse
from reportlab.pdfgen import canvas

from .models import UploadHistory


# ✅ CSV UPLOAD + ANALYTICS
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def upload_csv(request):

    file = request.FILES.get('file')

    if not file:
        return Response(
            {"error": "No file uploaded"},
            status=status.HTTP_400_BAD_REQUEST
        )

    try:
        df = pd.read_csv(file)

        # Validate required columns
        required_columns = ['Pressure', 'Temperature', 'Type']

        for col in required_columns:
            if col not in df.columns:
                return Response(
                    {"error": f"Missing required column: {col}"},
                    status=status.HTTP_400_BAD_REQUEST
                )

        summary = {
            "total_equipment": len(df),
            "avg_pressure": round(float(df['Pressure'].mean()), 2),
            "avg_temperature": round(float(df['Temperature'].mean()), 2),
            "type_distribution": df['Type'].value_counts().to_dict()
        }

        # ✅ SAVE TO DATABASE
        UploadHistory.objects.create(
            total_equipment=summary["total_equipment"],
            avg_pressure=summary["avg_pressure"],
            avg_temperature=summary["avg_temperature"],
            type_distribution=summary["type_distribution"]
        )

        # ✅ KEEP ONLY LAST 5 RECORDS
        history_count = UploadHistory.objects.count()

        if history_count > 5:
            ids_to_delete = UploadHistory.objects.order_by('uploaded_at')\
                        .values_list('id', flat=True)[:history_count - 5]

            UploadHistory.objects.filter(id__in=list(ids_to_delete)).delete()

        return Response(summary, status=status.HTTP_200_OK)

    except Exception as e:
        print("REAL ERROR:", str(e))   # ⭐ CRITICAL LINE
        return Response(
        {"error": str(e)},
        status=status.HTTP_400_BAD_REQUEST
    )



# ✅ HISTORY API
@api_view(['GET'])
def get_history(request):

    history = UploadHistory.objects.all()[:5]

    data = [
        {
            "total_equipment": record.total_equipment,
            "avg_pressure": record.avg_pressure,
            "avg_temperature": record.avg_temperature,
            "type_distribution": record.type_distribution,
            "uploaded_at": record.uploaded_at
        }
        for record in history
    ]

    return Response(data)


# ✅ PDF REPORT GENERATION
@api_view(['GET'])
def generate_pdf(request):

    latest = UploadHistory.objects.first()

    if not latest:
        return Response(
            {"error": "No history available"},
            status=status.HTTP_404_NOT_FOUND
        )

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="equipment_report.pdf"'

    p = canvas.Canvas(response)

    # ✅ Title
    p.setFont("Helvetica-Bold", 18)
    p.drawCentredString(300, 800, "Chemical Equipment Report")

    # Divider
    p.line(50, 780, 550, 780)

    p.setFont("Helvetica", 12)

    # Summary Section
    y = 740
    p.drawString(70, y, f"Total Equipment: {latest.total_equipment}")
    y -= 25
    p.drawString(70, y, f"Average Pressure: {latest.avg_pressure}")
    y -= 25
    p.drawString(70, y, f"Average Temperature: {latest.avg_temperature}")

    # Distribution Header
    y -= 40
    p.setFont("Helvetica-Bold", 13)
    p.drawString(70, y, "Equipment Type Distribution")

    p.setFont("Helvetica", 12)

    # Distribution Data
    for key, value in latest.type_distribution.items():
        y -= 22
        p.drawString(90, y, f"{key}: {value}")

    # Footer
    p.setFont("Helvetica-Oblique", 9)
    p.drawString(70, 40, "Generated by Chemical Equipment Visualizer")

    p.showPage()
    p.save()

    return response
